name: 'Aktualizuje issue body'
description: 'Prolinkuje s testovacím serverem'
inputs:
    token: # id of input
        description: 'Int issue number'
        required: true
    issue-number:  # id of input
        description: 'Int issue number'
        required: true
    pr-number: # id of input
        description: 'Int pr number'
        required: true
outputs:
    time: # id of output
        description: 'The time we greeted you'
runs:
    using: 'node12'
    main: 'dist/index.js'
