name: 'Aktualizuje issue body'
description: 'Prolinkuje s testovacím serverem'

inputs:
    token:
        description: 'Github token'
        required: true
    event:
        description: 'PR created event'
        required: true
    issue-regexp:
        description: 'Regular expression for issue detection'
        required: true
        default: 'Issue: #([0-9]+)'
    prepend-issue-message:
        description: 'Placeholders [[issueNumber]] [prNumber]]'
        default: ''
    append-issue-message:
        description: 'Placeholders [[issueNumber]] [prNumber]]'
        default: ''

outputs:
    issue-number:
        description: 'Parsed Issue number'
    pr-number:
        description: 'Parsed PR number'
    pr-body:
        description: 'PR body text'

runs:
    using: 'node12'
    main: 'dist/index.js'
