name: Přidání informací o testserveru do ISSUE

on:
  pull_request:
    types: [opened, reopened]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issuebody
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: 3
          issue-number: 1

      - name: "Vypsání dat"
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_BODY: ${{ github.event.pull_request.body }}
          GITHUB_CONTENT_JSON: ${{ toJson(github) }}
        run: |
          echo "PR number: $PR_NUMBER"
          echo "Body: $PR_BODY"
          regex="Issue\: \#([[:digit:]]+)"
          if [[ $PR_BODY =~ $regex ]]; then
            ISSUE_NUMBER=${BASH_REMATCH[1]}
            ISSUE_URL="https://api.github.com/repos/milous/actions-pr-issue-comment/issues/$ISSUE_NUMBER"

            ISSUE=$(curl --location --request GET $ISSUE_URL --header 'Content-Type: application/json' --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}')
            echo "issue:"
            echo $ISSUE[body]

            echo "cislo issue: ${BASH_REMATCH[1]}"
            echo "cislo issue v2: $ISSUE_NUMBER"
          fi
