name: Přidání informací o testserveru do ISSUE

on:
  pull_request:
    types: [opened, reopened]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: "Vypsání dat"
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_BODY: ${{ github.event.pull_request.body }}
          GITHUB_CONTENT_JSON: ${{ toJson(github) }}
        run: |
          echo "PR number: $PR_NUMBER"
          echo "Body: $PR_BODY"
          regex="Issue\: \#([[:digit:]]+)"
          if [[ $PR_BODY =~ $regex ]]; then
            ISSUE_NUMBER=${BASH_REMATCH[1]}
            echo "cislo issue: ${BASH_REMATCH[1]}"
            echo "cislo issue v2: $ISSUE_NUMBER"
          fi
