name: Přidání informací o testserveru do ISSUE

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: "Vypsání dat"
        env:
          GITHUB_CONTENT_JSON: ${{ toJson(github) }}
          GITHUB_JOB_JSON: ${{ toJson(job) }}
        run: |
          echo "$GITHUB_CONTENT_JSON"
          echo $GITHUB_JOB_JSON
          curl "https://www.seznam.cz/"
